/*
 * OpenPS3FTP vsh plugin — embedded HTTP server.
 *
 * Third renderer of the shared UI model (app/ui.h / app/ui.c): runs
 * the model poll loop (snapshot -> opftp_ui_poll) on its own thread
 * and serializes the model state to JSON for the web UI.
 *
 * Endpoints:
 *   GET  /            index.html   (embedded via bin2s on ps3;
 *                                  read from app/webui on host)
 *   GET  /style.css   app.js
 *   GET  /api/state   model snapshot JSON (see app/webui/app.js
 *                                  for the consumer contract)
 *   POST /api/cmd     {"action":"root","path":"..."} | {"action":"stop"}
 *
 * HTTP/1.0-style: read one request, respond, close.  Fine for a
 * browser polling once per second.
 *
 * Sockets come from the platform: on ps3 the plugin's netbridge.c
 * provides them (raw lv2 syscalls), on host they are POSIX.
 */
#include "opftp.h"
#include "ui.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

#ifdef OPFTP_PS3
#include <net/poll.h>
/* embedded assets: generated by ps3_bin2s into the build dir */
#include "index_html.h"
#include "style_css.h"
#include "app_js.h"
#else
#include <poll.h>
#endif

#define HTTPD_PORT_DEFAULT 8080
#define HTTPD_MAX_REQ 4096
#define HTTPD_BUF 16384
#define HTTPD_MAX_CONN 16

struct opftp_httpd {
    opftp_server_t* server;
    opftp_ui_t ui;
    uint16_t port;
    int listen_fd;
    opftp_pollset_t* poll;
    void* thread;            /* opftp_thread_create handle */
    char version[48];
    bool stop;
    uint64_t last_poll_us;
    /* accepted connections: fd + pollset handle */
    int conn_fd[HTTPD_MAX_CONN];
    int conn_hnd[HTTPD_MAX_CONN];
#ifndef OPFTP_PS3
    char asset_dir[256];   /* host harness: web assets on disk */
#endif
};
typedef struct opftp_httpd opftp_httpd_t;

static void http_send(int fd, const char* status, const char* ctype,
                      const char* body, size_t body_len);

/* ------------------------------------------------------------------ */
/* json string escaping (minimal: " \ and control chars)              */
/* ------------------------------------------------------------------ */

static void json_escape(char* out, size_t n, const char* s)
{
    size_t o = 0;
    for (; *s && o + 6 < n; s++) {
        unsigned char c = (unsigned char)*s;
        switch (c) {
        case '"':  out[o++] = '\\'; out[o++] = '"';  break;
        case '\\': out[o++] = '\\'; out[o++] = '\\'; break;
        case '\n': out[o++] = '\\'; out[o++] = 'n';  break;
        case '\r': out[o++] = '\\'; out[o++] = 'r';  break;
        case '\t': out[o++] = '\\'; out[o++] = 't';  break;
        default:
            if (c < 0x20)
                out[o++] = '?';
            else
                out[o++] = (char)c;
        }
    }
    out[o] = 0;
}

/* ------------------------------------------------------------------ */
/* /api/state serialization                                           */
/* ------------------------------------------------------------------ */

static int ui_client_idx(const opftp_ui_t* ui, const char* peer)
{
    for (int i = 0; i < OPFTP_UI_MAX_TRACK; i++)
        if (ui->trk[i].present && !strcmp(ui->trk[i].peer, peer))
            return i;
    return -1;
}

static void emit_state(const opftp_httpd_t* h, char* out, size_t n)
{
    const opftp_ui_t* ui = &h->ui;
    uint64_t now_us = (uint64_t)opftp_now_ms() * 1000ull;
    size_t o = 0;
    int i;

#define PUT(...) o += snprintf(out + o, n > o ? n - o : 0, __VA_ARGS__)

    PUT("{\"version\":\"%s\",\"running\":%s,\"port\":%u,\"root\":\"",
        h->version, ui->snap.started ? "true" : "false", ui->snap.port);
    { char esc[OPFTP_SNAPSHOT_PATH * 2]; json_escape(esc, sizeof(esc), ui->snap.root);
      PUT("%s", esc); }
    PUT("\",\"workers\":%d,\"uptime_s\":%llu,",
        ui->snap.workers,
        (unsigned long long)(now_us - ui->t0_us) / 1000000ull);
    PUT("\"session\":{\"xfers\":%llu,\"bytes\":%llu},",
        (unsigned long long)ui->session_xfers,
        (unsigned long long)ui->session_bytes);

    /* events: newest first */
    PUT("\"events\":[");
    for (i = 0; i < ui->ev_count; i++) {
        const opftp_ui_ev_t* e =
            &ui->events[(ui->ev_head - i + OPFTP_UI_MAX_EVENTS) % OPFTP_UI_MAX_EVENTS];
        char esc[72 * 2];
        json_escape(esc, sizeof(esc), e->text);
        if (i) PUT(",");
        PUT("{\"hh\":%u,\"mm\":%u,\"text\":\"%s\",\"warn\":%s}",
            e->hh, e->mm, esc, e->warn ? "true" : "false");
    }
    PUT("],");

    /* history: newest first */
    PUT("\"history\":[");
    for (i = 0; i < ui->hist_count; i++) {
        const opftp_ui_hist_t* hh =
            &ui->hist[(ui->hist_head - i + OPFTP_UI_MAX_HIST) % OPFTP_UI_MAX_HIST];
        char esc[OPFTP_SNAPSHOT_PATH * 2];
        json_escape(esc, sizeof(esc), hh->path);
        if (i) PUT(",");
        PUT("{\"op\":\"%s\",\"path\":\"%s\",\"bytes\":%llu,\"total\":%llu,"
            "\"hh\":%u,\"mm\":%u,\"result\":%d}",
            hh->op, esc, (unsigned long long)hh->bytes, (unsigned long long)hh->total,
            hh->hh, hh->mm, hh->result);
    }
    PUT("],");

    /* clients: from the live snapshot, enriched with model rate/idle */
    PUT("\"clients\":[");
    for (i = 0; i < ui->snap.num_clients; i++) {
        const opftp_snapshot_client_t* c = &ui->snap.clients[i];
        char esc_peer[128], esc_user[128], esc_cwd[OPFTP_SNAPSHOT_PATH * 2],
             esc_path[OPFTP_SNAPSHOT_PATH * 2];
        int t = ui_client_idx(ui, c->peer);
        double rate = 0.0;
        uint64_t idle_s = 0;
        if (t >= 0) {
            rate = ui->trk[t].rate;
            if (c->xfer_active)
                idle_s = (now_us - ui->trk[t].xfer_t0_us) / 1000000ull;
            else
                idle_s = (now_us - ui->trk[t].idle_reset_us) / 1000000ull;
        }
        json_escape(esc_peer, sizeof(esc_peer), c->peer);
        json_escape(esc_user, sizeof(esc_user), c->user);
        json_escape(esc_cwd, sizeof(esc_cwd), c->cwd);
        json_escape(esc_path, sizeof(esc_path), c->xfer_path);
        if (i) PUT(",");
        PUT("{\"peer\":\"%s\",\"user\":\"%s\",\"cwd\":\"%s\",\"logged_in\":%s,"
            "\"xfer_active\":%s,\"op\":\"%s\",\"path\":\"%s\","
            "\"bytes\":%llu,\"total\":%llu,\"rate\":%.1f,\"idle_s\":%llu}",
            esc_peer, esc_user, esc_cwd,
            c->logged_in ? "true" : "false",
            c->xfer_active ? "true" : "false",
            c->xfer_op[0] ? c->xfer_op : "",
            esc_path,
            (unsigned long long)c->xfer_bytes, (unsigned long long)c->xfer_total,
            rate, (unsigned long long)idle_s);
    }
    PUT("]}");
#undef PUT
}

/* ------------------------------------------------------------------ */
/* /api/cmd handling                                                  */
/* ------------------------------------------------------------------ */

static const char* find_json_str(const char* body, const char* key,
                                 char* out, size_t n)
{
    /* tiny JSON grabber for {"action":"...","path":"..."} */
    char pat[64];
    snprintf(pat, sizeof(pat), "\"%s\"", key);
    const char* p = strstr(body, pat);
    if (!p) return NULL;
    p = strchr(p + strlen(pat), '"');
    if (!p) return NULL;
    p++;
    size_t o = 0;
    while (*p && *p != '"' && o + 1 < n) {
        if (*p == '\\' && p[1]) p++;
        out[o++] = *p++;
    }
    out[o] = 0;
    return out;
}

static void handle_cmd(opftp_httpd_t* h, const char* body, char* out, size_t n)
{
    char action[32] = "";
    find_json_str(body, "action", action, sizeof(action));

    if (!strcmp(action, "stop")) {
        opftp_server_stop(h->server);
        snprintf(out, n, "{\"ok\":true}");
    } else if (!strcmp(action, "root")) {
        char path[OPFTP_SNAPSHOT_PATH] = "";
        if (find_json_str(body, "path", path, sizeof(path)) && path[0]) {
            int rc = opftp_server_set_root_runtime(h->server, path);
            snprintf(out, n, rc == 0 ? "{\"ok\":true}"
                                     : "{\"ok\":false,\"error\":\"%d\"}", rc);
        } else {
            snprintf(out, n, "{\"ok\":false,\"error\":\"path required\"}");
        }
    } else {
        snprintf(out, n, "{\"ok\":false,\"error\":\"unknown action\"}");
    }
}

/* ------------------------------------------------------------------ */
/* static asset lookup                                                */
/* ------------------------------------------------------------------ */

static int serve_asset(opftp_httpd_t* h, int fd, const char* path)
{
#ifdef OPFTP_PS3
    struct { const char* name; const unsigned char* data; unsigned int len; }
    assets[] = {
        { "",            index_html, index_html_size },
        { "style.css",   style_css,  style_css_size  },
        { "app.js",      app_js,     app_js_size     },
    };
    for (unsigned int i = 0; i < sizeof(assets) / sizeof(assets[0]); i++) {
        if (!strcmp(path, assets[i].name)) {
            const char* ct = !strcmp(path, "style.css") ? "text/css"
                           : !strcmp(path, "app.js")    ? "application/javascript"
                                                        : "text/html; charset=utf-8";
            http_send(fd, "200 OK", ct, (const char*)assets[i].data, assets[i].len);
            return 1;
        }
    }
#else
    /* host harness: serve straight from the webui dir */
    const char* names[] = { "index.html", "style.css", "app.js" };
    const char* cts[]   = { "text/html; charset=utf-8", "text/css", "application/javascript" };
    for (unsigned int i = 0; i < sizeof(names) / sizeof(names[0]); i++) {
        const char* want = i == 0 ? "" : names[i];
        if (strcmp(path, want)) continue;
        char full[512];
        snprintf(full, sizeof(full), "%s/%s", h->asset_dir, names[i]);
        FILE* f = fopen(full, "rb");
        if (!f) break;
        fseek(f, 0, SEEK_END);
        long len = ftell(f);
        fseek(f, 0, SEEK_SET);
        char* buf = malloc(len > 0 ? (size_t)len : 1);
        if (buf) {
            size_t got = fread(buf, 1, (size_t)len, f);
            http_send(fd, "200 OK", cts[i], buf, got);
            free(buf);
        }
        fclose(f);
        return 1;
    }
#endif
    return 0;
}

/* ------------------------------------------------------------------ */
/* connection handling                                                */
/* ------------------------------------------------------------------ */

static void http_send(int fd, const char* status, const char* ctype,
                      const char* body, size_t body_len)
{
    char head[256];
    int hl = snprintf(head, sizeof(head),
        "HTTP/1.0 %s\r\nContent-Type: %s\r\nContent-Length: %zu\r\n"
        "Cache-Control: no-cache\r\nConnection: close\r\n\r\n",
        status, ctype, body_len);
    send(fd, head, (size_t)hl, 0);
    if (body_len)
        send(fd, body, body_len, 0);
}

static void serve_client(opftp_httpd_t* h, int fd)
{
    char req[HTTPD_MAX_REQ + 1];
    size_t n = 0;

    /* read until end of headers (or buffer full) */
    while (n < HTTPD_MAX_REQ) {
        char tmp[512];
        int r = recv(fd, tmp, sizeof(tmp), 0);
        if (r <= 0) return;
        if ((size_t)r > sizeof(req) - 1 - n) r = (int)(sizeof(req) - 1 - n);
        memcpy(req + n, tmp, (size_t)r);
        n += (size_t)r;
        req[n] = 0;
        if (strstr(req, "\r\n\r\n") || strstr(req, "\n\n")) break;
    }
    req[n] = 0;

    /* method + path */
    char method[8] = "", path[128] = "", body[512] = "";
    if (sscanf(req, "%7s %127s", method, path) != 2) return;
    if (!strcmp(method, "POST")) {
        /* crude body grab: everything after the blank line */
        const char* b = strstr(req, "\r\n\r\n");
        if (!b) b = strstr(req, "\n\n");
        if (b) {
            b += (*b == '\r') ? 4 : 2;
            strncpy(body, b, sizeof(body) - 1);
        }
    }

    if (!strcmp(method, "GET")) {
        if (!strcmp(path, "/api/state")) {
            char buf[HTTPD_BUF];
            emit_state(h, buf, sizeof(buf));
            http_send(fd, "200 OK", "application/json", buf, strlen(buf));
        } else {
            const char* p = path + 1;   /* skip '/' */
            if (!*p || !strcmp(p, "index.html")) p = "";
            if (!serve_asset(h, fd, p))
                http_send(fd, "404 Not Found", "text/plain", "not found", 9);
        }
    } else if (!strcmp(method, "POST") && !strcmp(path, "/api/cmd")) {
        char out[512];
        handle_cmd(h, body, out, sizeof(out));
        http_send(fd, "200 OK", "application/json", out, strlen(out));
    } else {
        http_send(fd, "405 Method Not Allowed", "text/plain", "no", 2);
    }

    /* let the client read the reply before we close */
    opftp_pollset_wait(h->poll, 30);
}

/* ------------------------------------------------------------------ */
/* server thread: model poll loop + accept loop                       */
/* ------------------------------------------------------------------ */

static void httpd_thread(void* arg)
{
    opftp_httpd_t* h = arg;

    opftp_ui_init(&h->ui, (uint64_t)opftp_now_ms() * 1000ull);
    h->last_poll_us = h->ui.t0_us;
    h->ui.version = h->version;

    while (!h->stop) {
        int n, i;
        void* users[8];
        short events[8];

        /* model poll every ~1s */
        uint64_t now_us = (uint64_t)opftp_now_ms() * 1000ull;
        if (now_us - h->last_poll_us >= 1000000ull) {
            opftp_server_snapshot(h->server, &h->ui.snap);
            opftp_ui_poll(&h->ui, now_us);
            h->last_poll_us = now_us;
        }

        n = opftp_pollset_wait(h->poll, 250);
        if (n <= 0) continue;
        n = opftp_pollset_collect(h->poll, users, events, 8);
        for (i = 0; i < n; i++) {
            if (users[i] == (void*)(intptr_t)h->listen_fd) {
                /* listener is non-blocking (opftp_set_nonblock in
                 * create): drain the queue until EAGAIN, like the
                 * reactor's accept_clients() */
                int fd;
                int slot = -1;
                for (int k = 0; k < HTTPD_MAX_CONN; k++)
                    if (h->conn_fd[k] < 0) { slot = k; break; }
                while (slot >= 0 && (fd = accept(h->listen_fd, NULL, NULL)) >= 0) {
                    h->conn_fd[slot] = fd;
                    h->conn_hnd[slot] = opftp_pollset_add(h->poll, fd, POLLIN,
                                                          (void*)(intptr_t)fd);
                    slot = -1;
                    for (int k = 0; k < HTTPD_MAX_CONN; k++)
                        if (h->conn_fd[k] < 0) { slot = k; break; }
                }
            } else {
                int fd = (int)(intptr_t)users[i];
                int slot = -1;
                for (int k = 0; k < HTTPD_MAX_CONN; k++)
                    if (h->conn_fd[k] == fd) { slot = k; break; }
                serve_client(h, fd);
                if (slot >= 0) {
                    opftp_pollset_remove(h->poll, h->conn_hnd[slot]);
                    h->conn_fd[slot] = -1;
                    h->conn_hnd[slot] = -1;
                }
                opftp_close_fd(fd);
            }
        }
    }
}

/* ------------------------------------------------------------------ */
/* public API                                                         */
/* ------------------------------------------------------------------ */

opftp_httpd_t* opftp_httpd_create(opftp_server_t* s, const char* version,
                                  uint16_t port, const char* asset_dir)
{
    opftp_httpd_t* h = calloc(1, sizeof(*h));
    if (!h) return NULL;
    h->server = s;
    h->port = port ? port : HTTPD_PORT_DEFAULT;
    strncpy(h->version, version ? version : "?", sizeof(h->version) - 1);
#ifndef OPFTP_PS3
    if (asset_dir)
        strncpy(h->asset_dir, asset_dir, sizeof(h->asset_dir) - 1);
#endif
    for (int k = 0; k < HTTPD_MAX_CONN; k++)
        h->conn_fd[k] = -1;

    h->poll = opftp_pollset_create();
    if (!h->poll) { free(h); return NULL; }

    h->listen_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (h->listen_fd < 0) { opftp_pollset_destroy(h->poll); free(h); return NULL; }
    int one = 1;
    setsockopt(h->listen_fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof(one));

    struct sockaddr_in sa;
    memset(&sa, 0, sizeof(sa));
    sa.sin_family = AF_INET;
    sa.sin_port = htons(h->port);
    sa.sin_addr.s_addr = htonl(INADDR_ANY);
    if (bind(h->listen_fd, (struct sockaddr*)&sa, sizeof(sa)) != 0 ||
        listen(h->listen_fd, 4) != 0) {
        opftp_close_fd(h->listen_fd);
        opftp_pollset_destroy(h->poll);
        free(h);
        return NULL;
    }
    /* non-blocking listener so the accept drain loop can stop at
     * EAGAIN (same as the FTP reactor's listener) */
    opftp_set_nonblock(h->listen_fd);
    opftp_pollset_add(h->poll, h->listen_fd, POLLIN, (void*)(intptr_t)h->listen_fd);

    h->thread = opftp_thread_create(httpd_thread, h);
    if (h->thread == NULL) {
        opftp_close_fd(h->listen_fd);
        opftp_pollset_destroy(h->poll);
        free(h);
        return NULL;
    }
    return h;
}

void opftp_httpd_destroy(opftp_httpd_t* h)
{
    if (!h) return;
    h->stop = true;
    opftp_pollset_wake(h->poll);
    opftp_thread_join(h->thread);   /* free only after the thread exits */
    opftp_thread_destroy(h->thread);
    opftp_close_fd(h->listen_fd);
    opftp_pollset_destroy(h->poll);
    free(h);
}
